services:
  app:
    build: .
    ports:
      - "9011:9011"
  db:
    image: mariadb:10.6
    restart: always

    ports:
      - "9012:3306"
    environment:
      MARIADB_DATABASE: ml_advisor
      MARIADB_ROOT_PASSWORD: test
      TZ: Asia/Tokyo
    volumes:
      - ml-db-data:/var/lib/mysql

volumes:
  ml-db-data:
