services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "9011:9011"
  db:
    image: mariadb:10.6
    restart: always

    ports:
      - "9012:3306"
    environment:
      MARIADB_DATABASE: ml_advisor
      MARIADB_ROOT_PASSWORD: test
      TZ: Asia/Tokyo
    volumes:
      - ml-db-data:/var/lib/mysql

  janome:
    build: ./docker/janome/
    ports:
      - "9013:8000"
    tty: true
    volumes:
      - ./python:/root/work

volumes:
  ml-db-data:
